config/routes.rb
Rails.application.routes.draw do

  # home
  root to: 'gossips#index'

  get '/welcome/:first_name', to: 'static_pages#welcome'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'

  resources :gossips # routes for gossips
  resources :author, only: [:show]
  resources :city, only: [:show]
  resources :comment

  resources :sessions, only: [:new, :create, :destroy, :index]
  get 'sessions/welcome'
  get 'authorized', to: 'sessions#page_requires_login'

  resources :users, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { in: 10..1000 }
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true
  belongs_to :user
  has_many :join_table_tag_gossip
  has_many :tags, through: :join_table_tag_gossip
  has_many :comments
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :tag 
  belongs_to :gossip 
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossip
  has_many :gossips, through: :join_table_tag_gossip
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in? 
    !current_user.nil?
  end

  #def authorized
   #redirect_to 'gossips_path' unless logged_in?
  #end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def show
  end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossips = []
    City.all.each do |city|
      city.users.where(city_id: params[:id]).each do |user|
        user.gossips.each do |gossip|
          @gossips << gossip
        end
      end
    end
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  def index
   @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    gossip = Gossip.find(params[:gossip])
    @comment = Comment.new(gossip: gossip,user: User.last,content: params[:content])
    puts @comment
    if @comment.save 
      flash[:success] =  "Yes ton commentaire à bien été crée !"
      redirect_to gossip_path(id: Gossip.find(gossip.id))
    else
      flash[:error] =  "Commentaire invalide, minimum 10 characters"
      redirect_to gossip_path(id: Gossip.find(gossip.id))  #sinon, il render la view new (qui est celle sur laquelle on est déjà)  
    end
  end


  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(params)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def new
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.all.where(gossip_id: params[:id]).order("created_at DESC")
    @comment = Comment.new(gossip: @gossip, user: User.find(@gossip.user.id), content: "")
  end

  def create
    @gossip = Gossip.new(title: params['gossip_title'], content: params['gossip_content'], user: User.find_by(first_name: 'anonymous')) # avec xxx qui sont les données obtenues à partir du formulaire
    if @gossip.save # essaie de sauvegarder en base @gossip
      flash[:success] =  "Yes ton potin à bien été crée !"
      redirect_to action: "index"
    else
      flash.now[:error] =  "Champs invalides"
      render :new  #sinon, il render la view new (qui est celle sur laquelle on est déjà)  
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    # ou: params_potin = params.require(:gossip).permit(:title, :content)
    # et: if @gossip.update(params_potin, user:....)
    if @gossip.update(title: params[:gossip][:title], content: params[:gossip][:content], user: User.find_by(first_name: 'anonymous'))
      flash[:notice] =  "Le potin à bien été edité !"
      redirect_to action: "show", id: (params[:id])
    else
      flash.now[:error] =  "Champs invalides"
      render :edit
    end
  end

  def destroy
    goss = Gossip.find(params[:id])
    goss.destroy
    flash[:alert] =  "Le potin a été supprimé :o"
    redirect_to action: "index"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  #skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    puts "$$$"*20
    puts params[:password]
    puts "$$$"*20
    puts @user.authenticate(params[:password])
    puts "$$$"*20
    if @user && @user.authenticate(params[:password])
       sessions[:user_id] = @user.id
       redirect_to gossips_path
    else
      flash[:alert] = 'Invalid email/password combination'
       redirect_to new_session_path
    end
 end

  def destroy
  end

  def page_requires_login
  end

end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController

  #skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:email, :password))
    session[:user_id] = @user.id
    redirect_to gossips_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/city/show.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>
    <br />
    <div class = "text-center"><h4> Voici la liste actuelle des potins écrits par les auteurs de la ville <%= @city.name%>: </h4></div>
    <br />
    <div class="container-potin row justify-content-center">
    <% id_potin = 1%>
    <% @gossips.each do |gossip| %>
      <div class="card mt-2 text-center" style="width: 20rem;">
        <h6 class="card-header"><%= User.find_by(id:gossip.user_id).first_name %></h6>
        <div class="card-body">
          <h6 class="card-title"><%= gossip.content %></h6>
          <a href="<%= gossip_path(gossip.id) %>" class="btn btn-primary">Gossip n° <%=id_potin%></a>
        </div>
      </div>
      <% id_potin += 1%>
    <% end %>
  </div>


  </body>
</html>

app/views/comment/edit.html.erb
<h1>Comment#edit</h1>
<p>Find me in app/views/comment/edit.html.erb</p>

<div class = "text-center"><a href="<%= comment_path(@comment.id) %>" class="btn btn-danger" data-confirm="Etes vous sur de vouloir supprimer ce commentaire?" data-method='DELETE'>Détruire à jamais ce commentaire</a></div>

app/views/gossips/edit.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>
    <br />
    <div class="row justify-content-center ">
      <h1>Tu peux changer les infos de ce potin:</h1>
    </div>
    <br />
    <div class="container-potin row justify-content-center ">
      <div class="card mt-2 text-center" style="width: 30rem;">
        <div class="card-body">
          <%= form_for@gossip do |f| %>
            <label for="fname">Titre: </label>
            <%= f.text_field :title %>
            <br />
            <label for="fname">Contenu: </label>
            <%= f.text_field :content %>
            <br />
            <%= submit_tag "Enregistrer Potin Edité" %>
          <% end%>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/gossips/index.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>
    <div class="col justify-content-center">
      <div class = "text-center"><h1>BIENVENUE!</h1></div>
      <br /> 
      <div class = "text-center"><h4> Tu peux choisir de créer un nouveau potin : </h4></div>
      <div class = "text-center"><a href="<%= new_gossip_path %>" class="btn btn-dark">Nouveau Potin !</a></div>
      <br /> <br />
      <div class = "text-center"><h4> Voici la liste actuelle des potins : </h4></div>
    </div>
    <div class="container-potin row justify-content-center">
      <% id_potin = 1%>
      <% @gossips.each do |gossip| %>
        <div class="card mt-2 text-center" style="width: 20rem;">
          <h6 class="card-header"><%= User.find_by(id:gossip.user_id).first_name %></h6>
          <div class="card-body">
            <h6 class="card-title"><%= gossip.content %></h6>
            <a href="<%= gossip_path(gossip.id) %>" class="btn btn-primary">Gossip n° <%=id_potin%></a>
          </div>
        </div>
        <% id_potin += 1%>
      <% end %>
    </div>


  </body>
</html>

app/views/gossips/new.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>
    <br />
    <div class="row justify-content-center ">
      <h1>Balance le nouveau potin :</h1>
    </div>
    <br />
    <div class="container-potin row justify-content-center ">
      <div class="card mt-2 text-center" style="width: 20rem;">
        <div class="card-body">
          <%= form_tag url_for(action: 'create'), method: "post" do %>
            <label for="fname">Titre: </label>
            <input type="text" name="gossip_title">
            <br /> 
            <label for="fname">Contenu: </label>
            <input type="text" name="gossip_content">
            <br />
            <%= submit_tag "Enregistrer Potin" %>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/gossips/show.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>
    <div class = "text-center"><h1>Bienvenue sur la page du potin !</h1></div>
    <div class="container-potin row justify-content-center">
      <div class="card mt-2 text-center" style="width: 30rem;">
        <% gossip = Gossip.find(params[:id].to_i) %>
        <h6 class="card-header">Titre:     <%= gossip.title %> </h6>
        <div class="card-body">
          <div class="text-left"><h7>Contenu : <%= gossip.content %></h7></div>
          <br>
          <div class="text-left"><h7>Crée le : <%= gossip.created_at %></h7></div>
          <% id_user = User.find_by(id:gossip.user_id).id %>
          <% id_city = User.find_by(id:gossip.user_id).city_id %>
          <br>
          <a href="<%= city_path(id_city) %>" class="btn btn-primary">Ville : <%= City.find_by(id: id_city).name %></a>
          <a href="<%= author_path(id_user) %>" class="btn btn-primary"> Auteur : <%=User.find_by(id:gossip.user_id).first_name %></a>
        </div>
      </div>
    </div>
    <br>
    <div class = "text-center"><a href="<%= edit_gossip_path(gossip.id) %>" class="btn btn-dark">Editer ce potin</a></div>
    <br />
    <div class = "text-center"><a href="<%= gossip_path(gossip.id) %>" class="btn btn-danger" data-confirm="Etes vous sur de vouloir supprimer ce potin?" data-method='DELETE'>Détruire à jamais ce potin</a></div>
    <br /> <br />


    <!-- Add a comment -->
    <div class = "text-center"><h2>Commentaires : </h2></div>
    <div class="container-potin row justify-content-center ">
      <div class="card mt-2 text-center" style="width: 30rem;">
        <div class="card-body">
          <%= form_tag comment_index_path(gossip: @gossip), method: "post" do %>
            <label for="fname">Nouveau commentaire: </label>
            <input type="text" name="content">
            <br /> 
            <%= submit_tag "Sauvegarder commentaire" %>
          <% end %>
        </div>
      </div>
    </div>

    <!-- List Comments -->
    <div class="container-comment row justify-content-center">
      <% id_potin = 1%>
      <% @comments.each do |comment| %>
        <div class="card mt-2 text-center" style="width: 20rem;">
          <h6 class="card-header"><%= User.find_by(id:comment.user_id).first_name %></h6>
          <div class="card-body">
            <h6 class="card-title"><%= comment.content %></h6>
            <a href="<%= edit_comment_path(comment.id) %>" class="btn btn-dark"></i> Editer</a>
          </div>
        </div>
        <% id_potin += 1%>
      <% end %>
    </div>

    </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :email%><br>
  <%= f.text_field :email%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>